version: '3.8'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: .
      dockerfile: stock-app/Dockerfile
    depends_on:
      - mongo

  backend:
    build:
      context: .
      dockerfile: stock-backend/Dockerfile
    depends_on:
      - mongo
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
